server:
  port: 8072
spring:
  application:
    name: "shopee-eureka-server"
  config:
    import: "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true