eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

#Logging
logging:
  #  level:
  #    org:
  #      springframework:
  #        security: TRACE
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"